on: [push]

jobs:
   local_test_lasttag:
     runs-on: ubuntu-latest
     name: Test local action without fixed version
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Test local action
         id: local-action
         uses: ./
         with:
           upstream_repo: sysdiglabs/charts
           local_patch_dir: tests/sysdiglabs/charts
    outputs:
      used_tag: ${{ steps.local-action.outputs.tag }}
      used_lates: ${{ steps.local-action.outputs.latest }}

   local_test_fixed:
     runs-on: ubuntu-latest
     name: Test local action with fixed version
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Test local action
         id: local-action
         uses: ./
         with:
           upstream_repo: sysdiglabs/charts
           local_patch_dir: tests/sysdiglabs/charts
           upstream_ref: master
    outputs:
      used_tag: ${{ steps.local-action.outputs.tag }}
      used_lates: ${{ steps.local-action.outputs.latest }}
