on: [push]

jobs:
   local_test_lasttag:
     runs-on: ubuntu-latest
     name: Test local action without fixed version
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Test local action
         id: local-action
         uses: ./
         with:
           upstream_repo: sysdiglabs/kube-psp-advisor
           local_patch_dir: tests/sysdiglabs/kube-psp-advisor
     outputs:
       used_tag: ${{ steps.local-action.outputs.tag }}
       used_latest: ${{ steps.local-action.outputs.latest }}

   local_test_fixed:
     runs-on: ubuntu-latest
     name: Test local action with fixed version
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Test local action
         id: local-action
         uses: ./
         with:
           upstream_repo: sysdiglabs/kube-psp-advisor
           local_patch_dir: tests/sysdiglabs/kube-psp-advisor
           upstream_ref: master
     outputs:
       used_tag: ${{ steps.local-action.outputs.tag }}
       used_latest: ${{ steps.local-action.outputs.latest }}

   print_results:
    runs-on: ubuntu-latest
    needs: [local_test_lasttag, local_test_fixed]
    steps:
    - run: |
        echo "local_test_lasttag: ${{ needs.local_test_lasttag.outputs.used_tag }},${{ needs.local_test_lasttag.outputs.used_latest }}"
        echo "local_test_fixed: ${{ needs.local_test_fixed.outputs.used_tag }},${{ needs.local_test_fixed.outputs.used_latest }}"
        echo "semver_fixed: ${{ needs.local_test_fixed.outputs.major }}, ${{ needs.local_test_fixed.outputs.minor }}, ${{ needs.local_test_fixed.outputs.patch }}"
        echo "semver_lasttag: ${{ needs.local_test_lasttag.outputs.major }}, ${{ needs.local_test_lasttag.outputs.minor }}, ${{ needs.local_test_lasttag.outputs.patch }}"
      shell: bash
